# Generated by Django 4.2 on 2024-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableMatrixModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=100)),
                ('requesttype', models.CharField(max_length=100)),
                ('olddevice', models.CharField(max_length=100)),
                ('oldmodel', models.CharField(max_length=100)),
                ('rrd', models.DateField()),
                ('ipn', models.CharField(max_length=100)),
                ('cpn', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=100)),
                ('pm', models.CharField(max_length=100)),
                ('newdevice', models.CharField(max_length=100)),
                ('newmodel', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('clli', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('power_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('rack_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('dcs_comment', models.TextField(blank=True, null=True)),
                ('cable_trace_requested_date', models.DateField(blank=True, null=True)),
                ('cable_trace_received_date', models.DateField(blank=True, null=True)),
                ('tickets_required', models.CharField(blank=True, choices=[('EMAIL', 'EMAIL'), ('ESS', 'ESS'), ('ITONS', 'ITONS'), ('AORTS', 'AORTS')], max_length=20, null=True)),
                ('tickets_requested_date', models.DateField(blank=True, null=True)),
                ('tickets_requested_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tickets_closed_date', models.DateField(blank=True, null=True)),
                ('cable_trace_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('cable_trace_comment', models.TextField(blank=True, null=True)),
                ('network_design_start_date', models.DateField(blank=True, null=True)),
                ('network_design_close_date', models.DateField(blank=True, null=True)),
                ('network_design_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('network_design_comment', models.TextField(blank=True, null=True)),
                ('cable_matrix_started_date', models.DateField(blank=True, null=True)),
                ('cable_matrix_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('cable_matrix_completed_date', models.DateField(blank=True, null=True)),
                ('cable_matrix_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
