# Generated by Django 4.2 on 2024-07-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_cablematrixmodel_cable_matrix_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cablematrixmodel',
            old_name='status',
            new_name='dcs_status',
        ),
    ]
