# Generated by Django 4.2 on 2024-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_status_cablematrixmodel_dcs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='rrd',
            field=models.CharField(max_length=100),
        ),
    ]
