# Generated by Django 4.2 on 2024-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_cablematrixmodel_rrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='request_id',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
