# Generated by Django 4.2 on 2024-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_cablematrixmodel_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='cable_matrix_comment',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='cable_matrix_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet to Work', 'Yet to Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='cable_trace_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet to Work', 'Yet to Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='dcs_comment',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='dcs_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet to Work', 'Yet to Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='network_design_comment',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='network_design_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet to Work', 'Yet to Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='power_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet to Work', 'Yet to Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='rack_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet to Work', 'Yet to Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='requested_date',
            field=models.CharField(blank=True, default='0/0/0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='tickets_requested_id',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='tickets_required',
            field=models.CharField(blank=True, choices=[('EMAIL', 'EMAIL'), ('ESS', 'ESS'), ('ITONS', 'ITONS'), ('AORTS', 'AORTS')], default='NA', max_length=20),
        ),
    ]
