# Generated by Django 4.2 on 2024-07-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_cablematrixmodel_cable_matrix_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='cable_matrix_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='cable_trace_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='dcs_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='network_design_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='power_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='rack_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
