# Generated by Django 4.2 on 2024-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_navitem_subnavitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='rrd',
            field=models.DateField(),
        ),
    ]
