# Generated by Django 4.2 on 2024-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_subnavitem_parent_nav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrixmodel',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
