# Generated by Django 5.0.7 on 2024-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_cablematrixmodel_device_installation_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablematrixmodel',
            name='port_assignment_comment',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AddField(
            model_name='cablematrixmodel',
            name='port_assignment_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not Required', 'Not Required'), ('Yet To Work', 'Yet To Work'), ('Not yet Started', 'Not yet Started'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cablematrixmodel',
            name='port_tickets_closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cablematrixmodel',
            name='port_tickets_requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cablematrixmodel',
            name='port_tickets_requested_id',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='cablematrixmodel',
            name='port_tickets_required',
            field=models.CharField(blank=True, choices=[('EMAIL', 'EMAIL'), ('ESS', 'ESS'), ('ITONS', 'ITONS'), ('AORTS', 'AORTS')], max_length=20, null=True),
        ),
    ]
